#spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/admin
server:
  port: 8611
spring:
  application:
    name: nacos-consumer-1
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    enabled: true